-- MySQL Script generated by MySQL Workbench
-- Mon May  8 02:18:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema try
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema try
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `try` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `try` ;

-- -----------------------------------------------------
-- Table `try`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`countries` (
  `id_country` BIGINT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(255) NOT NULL,
  `region` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`users` (
  `id_user` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`images` (
  `id_image` BIGINT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `car` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_image`))
ENGINE = InnoDB
AUTO_INCREMENT = 91
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`cars` (
  `id_car` BIGINT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `model` VARCHAR(255) NOT NULL,
  `year_of_issue` INT NOT NULL,
  `transmission` VARCHAR(255) NOT NULL,
  `volume` DOUBLE NOT NULL,
  `body` VARCHAR(255) NOT NULL,
  `drive` VARCHAR(255) NOT NULL,
  `engine_type` VARCHAR(255) NOT NULL,
  `mileage` INT NOT NULL,
  `price` INT NOT NULL,
  `country_id` BIGINT NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `dealer_id` BIGINT NOT NULL,
  `fav` INT NULL DEFAULT NULL,
  `image` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_car`),
  INDEX `fk_car_id_country` (`country_id` ASC) VISIBLE,
  INDEX `fk_car_image` (`image` ASC) VISIBLE,
  INDEX `fk_car_id_user` (`dealer_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_id_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `try`.`countries` (`id_country`),
  CONSTRAINT `fk_car_id_user`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `try`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_car_image`
    FOREIGN KEY (`image`)
    REFERENCES `try`.`images` (`id_image`))
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`comments` (
  `id_comment` BIGINT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NOT NULL,
  `id_car` BIGINT NOT NULL,
  `id_user` BIGINT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_id_user` (`id_user` ASC) VISIBLE,
  INDEX `fk_comment_id_car` (`id_car` ASC) VISIBLE,
  CONSTRAINT `fk_comment_id_car`
    FOREIGN KEY (`id_car`)
    REFERENCES `try`.`cars` (`id_car`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comment_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `try`.`users` (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`companies` (
  `id_company` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `id_user` BIGINT NOT NULL,
  PRIMARY KEY (`id_company`),
  INDEX `fk_company_id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_company_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `try`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`favorites` (
  `id_favorite` BIGINT NOT NULL AUTO_INCREMENT,
  `dealer` BIGINT NOT NULL,
  `id_car` BIGINT NOT NULL,
  `id_user` BIGINT NOT NULL,
  PRIMARY KEY (`id_favorite`),
  INDEX `fk_fav_id_car` (`id_car` ASC) VISIBLE,
  INDEX `fk_fav_id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_fav_id_car`
    FOREIGN KEY (`id_car`)
    REFERENCES `try`.`cars` (`id_car`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fav_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `try`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`roles` (
  `id_key` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` INT NOT NULL,
  `id_user` BIGINT NOT NULL,
  PRIMARY KEY (`id_key`),
  UNIQUE INDEX `UK_ompmi3bd49gpmx4syhdig6yeh` (`login` ASC) VISIBLE,
  INDEX `fk_key_id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_key_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `try`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `try`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `try`.`sellers` (
  `id_seller` BIGINT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `id_user` BIGINT NOT NULL,
  PRIMARY KEY (`id_seller`),
  INDEX `fk_seller_id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_seller_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `try`.`users` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
